on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
    - name: Create GitHub Release
      if: success() && matrix.os == 'ubuntu-latest'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ github.ref }}"
        release_name: "${{ github.ref }}"
    - name: Publish
      if: success() && matrix.os == 'ubuntu-latest'
      run: npm run deploy
      env:
        VSCE_PAT: ${{secrets.VSCE_PAT}}

